language: node_js
addons:
  sauce_connect: true
env:
  global:
env:
  global:
    - secure: Hx6LLjjABIhD2Em96GRxYthAfAmpOzzQcmSgcts220P/bzT/8Pz1AQDWXzxlZ6Z5zeQWuQH1Vu2dUtV2EFZOeNUnAXXLz8tdnKUViLUTgOv0zZsZPOl/idw4qgIsZPP2H3Pwk4w7qz3K2j62gySWNG8/ZQA0+4xZRjSe+j67k4/kiYPuf9BkhghWe2pEQsdCpltJSS8UKpYGFV0LWAJveIj2Dpe/VU6vm3WvjEu/OEZpSQEIX9egTNw0VJKjBKV8M6aEsCpph9wv3dys1KzAB/kDfm4L8oSrtU/RFRR8U8KQkvHkppvyG8spFecjfSK4HTlb2uujXQHK3pVe5zShtDWIQ7Q7k7IXNAf8ZOuC7TqGTNAqedwnJTfur3Qemfbmvdb9vipxaJxwAjIp2Gb+WiD/5HbUy2pmWyO/y6NIoOXsTa8eGvAKbvUCUKS14J9Lko8BsH5XuZa/2v3+ypnN/PY82l4TyjCFfSKRPs3iqsWV0i/noeyoihm2z2QRra+U3+iY30bs2or262733lhC6hjE2qcpcT1j202lahis2HOr5bQFWz+G5ohHzkk+m95p4/gw95vliMZHTQKYjnJGw+M4KqSPu8UayBYnxmAPGyigXRpkHSp0GYNBkQiRq2GByQJkZEp5IE4CEh6hocfrHk/vRElKgQxpa5Zonx6cfaw=
    - secure: KOOewfm8rlgAUy5LsEkd3ptC3ZTud6apa5tkyr/jZXSnTVNVYESnpKP4m22bbpm+Rk9Z2tRmfA6qPG3ahIqfd0jS0MjJwZhCqX1jUvqD7iOKxuXH6DQcuvbfbJB+LY75fTzt0KfWVstIPjrgKA8aX9mNXqrt4FYYtVfJAAuSq6j4Ah26Z+UNFIrUu4GT4/PwB9CoVDZV43Wx7ezPIjcQ60tCve6BQv9Vg/LPpnoU6TCMcuFklVdn/UYS+u3eF7kPgcHBtAD/auQfnc+QJ96CNJyDKDHd1fUl0FG9QRQFiq0WfUJKdu8jJOVzozyrAjig1XQjLLxoZ31uX8U3AXqqwZveblf9k7qmn1alHCv63rEriHL065/foOQVW1bIGZrg9ZVisWfiG9biXu1Z5J3745S0qLy73nlfWa09r13LW2KPjd6rTQJ73WKXmttYtzkZ+aYjfVlFgbCGA8csbbFy1FVmos5afK9K6mgfi/DzxqBS7TRqIrNcQohLBBPeWhMPwyYofPcYEhz4R4WhskVWSPXHZOzXAFnnDEfODxxwA0u73g6kChfjXk/P5E9+GueYWm4+VjjEaYQKI7fy5XiK1L5XrcEI5FLDfVJGOngQhKcl12KGK1TdPWnOM9LsJ5WjX7iTt25JJmeEh6JstRQVkSco7ip357zBGqK0tPLAdXE=
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
node_js:
    - "0.12"
